### ISSUE TITLE
Add additional context to the default policy invocations

### ISSUE THREAD

**Issue by yonjah** [WICG/trusted-types#131]
Hi. I just finished reading the description of the API and it looks very interesting.

I think the main disadvantage I find with it is that if you use a framework you
don't really have control on how many of this sinks are being set.

I had similar issue with CSP where jQuery and other libraries I was loading we're injecting some code that broke the CSP policy and basically meant it lost most of it's value.

But reading this suggestion made me think. is it possible to just set a callback for all the sinks ?
So instead of having some fixed lock function that checks if a value is an instance of trustedType have a user defined function.
I assume the header will have to be something similar to 
```
Content-Security-Policy: trusted-set-method sinkPreSet
```

if the the global object has `setPreSet` method defined it will be called before any setting is happening.
This method will need to get the `sink`, `element`, `value` as  arguments and it's return value will be the actual value that will be set.

Having this control the app developer can mix whitelists, blacklist and trusted types depending on the context.

Now I can for example whitelist inline code my libraries inject, but require that all other values (coming from my own code) will be an instance of trusted types.

I can also decide to log / throw when a specific context fails to validate so I can find the actual injection vector or badly set value instead of just silently reject the value.

**Comment by koto** [comment]
Yes, we thinking about that. What you described can be implemented in a [default policy](https://wicg.github.io/trusted-types/dist/spec/index.html#default-policy-hdr) with some additional context when called (element, attr name). 

FWIW, for now the shape of the default policy is the most controversial and volatile part of the specification, and we're purposefully not advertising it yet. The problem here is that it indeed facilitates migration of existing code but at the same time has a tendency to grow into an unreviewable mess (it has to accept everything that your dependencies can potentially set), and introduces subtle bugs into your code - it's like changing the prototype of base JS objects, an antipattern (but with security benefits). We're think on a way to make it less-global and more-local to the code

**Comment by koto** [comment]
I renamed the issue, as this is what is missing from the current design - and adding that would fullfill your requirements. Thanks!

**Comment by koto** [comment]
#191 introduces `sink` parameter to a few algorithms. Currently it's an empty string, but we'll likely add it as an attribute to `TrustedTypes` extended attribute (which annotates the sinks).
