### ISSUE TITLE
Can URL policies be defined to use `URL` instead of `DOMString`?

### ISSUE THREAD

**Issue by briansmith** [WICG/trusted-types#150]
Right now we have:

```
TrustedTypePolicy {
   ...
  [Unforgeable] TrustedScriptURL createScriptURL(DOMString input);
  [Unforgeable] TrustedURL createURL(DOMString input);
}
```

The README of the GitHub repo has this:

```
   createURL: (s) => { /* parse and validate the url. throw if non-conformant */ },
```

Do we expect that a good implementation of the policy would parse the URL in any way other than creating a `URL`? If not, then it seems like a good idea use `URL` instead of `DOMString` everywhere possible, so that (1) policies don't need to construct URLs itself, and (2) so the policy isn't tempted to use a dumber parser that doesn't consider all the intricacies of URL parsing, and (3) so that policies will have access to already-constructed and normalized representation of the origin (`URL.origin`), which we can encourage them to use for such checks, instead of using worse (less complete) checks.

**Comment by briansmith** [comment]
It also seems likely that somebody would accidentally use the wrong base URI to validate URL, because there are multiple plausible sources of a base URI available.

On the flip side, I did think of a plausible reason why one would not want to do this: `URL` can only represent absolute URI references. Thus, it would not be possible for the policy to enforce that "only relative URI references are used" or "all relative URI references must start with '/'" or similar schemes.

**Comment by briansmith** [comment]
FWIW, https://url.spec.whatwg.org/#url-apis-elsewhere says to not do this.

**Comment by koto** [comment]
Unfortunately, we can't use `URL` (either as an input to `createURL`, or as an output), due to the relative URL issue you mention. The identity policy `(s) => s` should not change the serialization of the  URL, as then the migration from strings to the API becomes much harder (e.g. tests relying on golden files break, some virtual DOM libraries might detect that the DOM needs to be perpetually updated, as the serialization has changed etc.).
