### ISSUE TITLE
Use once semantic

### ISSUE THREAD

**Issue by annevk** [WICG/trusted-types#175]
Should there be a way to restrict how many times a typed object can be used? E.g., to protect against scenarios as outlined at https://github.com/w3c/webappsec-csp/issues/392.

**Comment by mikesamuel** [comment]
Could be done in user code?

```js
const { singleUse, useUp } = (() => {
  const useOncePolicy = TrustedTypes.createPolicy('use-once');

  const used = new Set();

  function makeNonce() { ... }  // crypto.getRandomValues or something.

  /**
   * @param {TrustedScript} s
   * @return {TrustedScript}
   */
  function singleUse(script) {
    if (!TrustedTypes.isScript(script)) { throw ... }
    const nonce = makeNonce();
    return useOncePolicy.createScript(`
        if (useUp(${ JSON.stringify(nonce) }) { throw ... }
        ${ script }`
    );
  }

  function useUp(nonce) {
    if (used.has(nonce)) { return true; }
    used.add(nonce);
    return false;
  }

  return { singleUse, useUp };
})();
```

**Comment by annevk** [comment]
That only works for classic scripts that don't have `"use strict";`, right?

**Comment by mikesamuel** [comment]
@annevk, Good point.  Sticking `if ...` before the DirectivePrologues would make them parse as expressions instead.

That problem could be fixed by hoisting them since directive prologues are unlikely to affect the semantics of the `if`.

The code to do so might be tricky in practice to avoid changing the meaning of

```js
"use strict"  // no semicolon insertion before infix operator
+a
```

or

```js
"use strict"
/not_a_regular_expression/i
```

**Comment by koto** [comment]
Putting aside on whether this is doable in user code, TT objects could theoretically be "consumed" by sinks (e.g. by setting an internal slot value e.g. ``[[PreventUsage]]`` to true), but I'm feeling this would be really surprising to the authors, as strings (TT predecessors) do not behave like that. So this definitely should not be the default case for TT objects. It's unclear what value this would exactly bring - I can see scenarios where this might result in a vulnerability, but they seem quite artificial (so I guess I'm raising a similar argument to @dveditz in https://github.com/w3c/webappsec-csp/issues/392#issuecomment-491984629). 

So I guess - yes, we could support it, but I'm not convinced we should, because of added complexity, and the possibility that this would simply not be used by authors (i.e. authors who would use it are already aware of a gadgets vulnerable to reuse attacks, and can possibly counter them via other means).

**Comment by koto** [comment]
I'll close this for now, as we have no active plans to support it yet, but please comment if you feel strongly about it. It is possible to add such feature if there's demand for it.
