### ISSUE TITLE
Create commonly used and harmless constants like TrustedHTML.EMPTY

### ISSUE THREAD

**Issue by koto** [WICG/trusted-types#95]
It's often the case that the applications would want an empty string to assign it to `innerHTML`.  Consider exposing a TrustedHTML wrapping an empty string without needing a policy to create it, e.g. as a static property of `TrustedHTML` object.

**Comment by vrana** [comment]
The EMPTY constants seem fine but I'm opposed to TrustedURL.HASH. There's no reason to use `#` alone as URL. It's only used to put there (usually in a.href) something that is later ignored (because the event handler stops the propagation). Anything else would work too, e.g. TrustedURL.EMPTY. Using `#` and not stopping the propagation causes the page to jump to the top which is a poor experience and we shouldn't encourage that by adding a constant for `#`.

**Comment by koto** [comment]
Filed a request for `TrustedHTML.EMPTY` at https://bugs.chromium.org/p/chromium/issues/detail?id=936436

**Comment by mikesamuel** [comment]
Would a solution to issue #96 obviate this?

**Comment by xtofian** [comment]
> Would a solution to issue #96 obviate this?

I think so.

I'd lean towards making these sorts of constants not part of the standard, but rather leave it to a (reference) builder library to provide.  Either as explicit symbols, or via template literals, which would allow you to write
 ``` trustedHTML`` ``` and ``` trustedURL`#` ```.

**Comment by koto** [comment]
I'm for keeping `TrustedHTML.EMPTY` as part of the standard. It's an easy way to facilitate rewriting existing code that doesn't require to use policies. For example, code linters might automatically refactor the code without any side-effects (assuming some minimal polyfill exists, or the replacement tests for the existence of the property first).

**Comment by koto** [comment]
The empty HTML constant was implemented in http://crbug.com/936436. Due to naming conventions and other concerns it will be available at the factory level, so currently:

```
const html = TrustedTypes.emptyHTML
```

(tests at https://github.com/web-platform-tests/wpt/blob/master/trusted-types/TrustedTypePolicyFactory-constants.tentative.html).

I'll follow up with the polyfill implementation.
